version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db_store
    environment:
      - POSTGRES_DB=db_ecommerce
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
